---
ips:
- AUS: '203.89.226.24'
- IRL: '185.24.232.225'
- GBR: '217.144.144.211'
- CAN: '104.244.197.245'
- USA: '8.8.8.8'
- SGP: '165.21.83.88'
- ESP: '212.36.64.16'
- HKG: '202.180.160.1'
- JPN: '210.248.255.82'
- NZL: '202.89.49.92'
- ITA: '217.22.209.254'
- RUS: '81.95.138.218'
- IDN: '114.7.10.46'
- IND: '61.8.131.204'
